[loadbalancer]
lb-01 ansible_host=10.10.10.10

[webservers]
web-01 ansible_host=10.10.20.11
web-02 ansible_host=10.10.20.12

[appservers]
app-01 ansible_host=10.10.20.21

[database]
db-01 ansible_host=10.10.20.31

[monitoring]
monitor-01 ansible_host=10.10.20.41

[all:vars]
ansible_user=ariel
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[infra]
infra-01 ansible_host=10.10.10.5
